import { db } from "../firebase.config";
import { collection, doc, getDoc, getDocs } from "firebase/firestore";
import { getCollectionName, getEnvMode } from "../utils/envMode";
import { functions } from "../firebase.config";
import { httpsCallable } from "firebase/functions";
import { createOperationId } from './inventoryOperationsService';

const CUSTOMER_FIELDS = [
    'name',
    'default_customer_type',
    'bridge_target'
];

const customerFields = (customerData = {}) => Object.fromEntries(
    CUSTOMER_FIELDS
        .filter(field => customerData[field] !== undefined)
        .map(field => [field, customerData[field]])
);

const callCustomerOperation = async (functionName, payload) => {
    const callable = httpsCallable(functions, functionName);
    const response = await callable({
        ...payload,
        environment: getEnvMode(),
        operation_id: createOperationId()
    });
    return response.data;
};

export const customerService = {
    /**
     * Create or update a registered customer. IDs are generated by the server
     * for new customers and are immutable afterwards.
     */
    saveCustomer: async (customerData) => {
        const customerId = customerData.customer_id || customerData.id || null;
        const fields = customerFields(customerData);
        if (customerId) {
            const result = await callCustomerOperation('updateCustomer', {
                customer_id: customerId,
                customer: fields
            });
            return result.customer_id;
        }

        const result = await callCustomerOperation('createCustomer', { customer: fields });
        return result.customer_id;
    },

    /**
     * Hide a customer from operational screens without touching the orders that
     * already reference it.
     */
    archiveCustomer: async (customerId) => {
        if (!customerId) return;
        await callCustomerOperation('archiveCustomer', { customer_id: customerId });
    },

    getAllCustomers: async ({ includeArchived = false } = {}) => {
        const col = getCollectionName("customers");
        const snapshot = await getDocs(collection(db, col));
        return snapshot.docs
            .map(d => ({ ...d.data(), id: d.id }))
            .filter(customer => includeArchived || customer.active !== false)
            .sort((a, b) => String(a.name || '').localeCompare(String(b.name || '')));
    },

    getCustomerById: async (customerId) => {
        if (!customerId) return null;
        const col = getCollectionName("customers");
        const snapshot = await getDoc(doc(db, col, customerId));
        if (!snapshot.exists()) return null;
        return { ...snapshot.data(), id: snapshot.id };
    }
};
