import { db } from "../firebase.config";
import { collection, doc, getDoc, getDocs } from "firebase/firestore";
import { getCollectionName, getEnvMode } from "../utils/envMode";
import { functions } from "../firebase.config";
import { httpsCallable } from "firebase/functions";
import { createOperationId } from './inventoryOperationsService';

export const PRODUCT_CATEGORIES = [
    "Beras",
    "Minyak, Mentega & Lemak",
    "Tepung",
    "Saus, Kecap & Sambal",
    "Bumbu & Bahan Masak",
    "Lainnya"
];

const PRODUCT_FIELDS = [
    'name',
    'base_unit',
    'bulk_unit_name',
    'bulk_unit_conversion',
    'cost_price',
    'price_regular',
    'price_premium',
    'price_star',
    'image_url',
    'category',
    'needs_stock_check'
];

const productFields = (productData = {}) => Object.fromEntries(
    PRODUCT_FIELDS
        .filter(field => productData[field] !== undefined)
        .map(field => [field, productData[field]])
);

const callProductOperation = async (functionName, payload) => {
    const callable = httpsCallable(functions, functionName);
    const response = await callable({
        ...payload,
        environment: getEnvMode(),
        operation_id: createOperationId()
    });
    return response.data;
};

export const productService = {
    /**
     * Create or update a product. IDs are generated by the server for new products
     * and are immutable for existing products.
     */
    saveProduct: async (productData) => {
        const productId = productData.product_id || productData.id || null;
        const fields = productFields(productData);
        if (productId) {
            const result = await callProductOperation('updateProduct', {
                product_id: productId,
                product: fields
            });
            return result.sku;
        }

        if (productData.sku) throw new Error('ID produk dibuat otomatis dan tidak boleh diisi manual.');
        const result = await callProductOperation('createProduct', { product: fields });
        return result.sku;
    },

    /**
     * Backward-compatible alias: products are archived so historical inventory
     * and transaction snapshots keep resolving safely.
     */
    deleteProduct: async (sku) => {
        if (!sku) return;
        await callProductOperation('archiveProduct', { product_id: sku });
    },

    /**
     * Hide a product from operational screens without deleting its stock or history.
     */
    archiveProduct: async (sku) => {
        if (!sku) return;
        await callProductOperation('archiveProduct', { product_id: sku });
    },

    /**
     * Fetch all products
     */
    getAllProducts: async ({ includeArchived = false } = {}) => {
        const col = getCollectionName("products");
        const snapshot = await getDocs(collection(db, col));
        return snapshot.docs
            .map(d => ({ id: d.id, ...d.data() }))
            .filter(product => includeArchived || product.active !== false);
    },

    /**
     * Get single product by SKU
     */
    getProductBySku: async (sku) => {
        const col = getCollectionName("products");
        const docRef = doc(db, col, sku);
        const docSnap = await getDoc(docRef);
        if (docSnap.exists()) {
            return { id: docSnap.id, ...docSnap.data() };
        }
        return null;
    },

    /**
     * Calculate unit price based on validation logic
     * Logic: "If qty < 10, price is X. If qty >= 10, price is Y."
     * Assumes price_tiers is [{ min_qty: number, price: number }]
     */
    calculatePrice: (product, customerType = 'regular') => {
        // Default to 0 if product is invalid
        if (!product) return 0;

        // Normalize customer type
        const type = customerType.toLowerCase();

        // Return specific price based on type
        if (type === 'star') return Number(product.price_star || 0);
        if (type === 'premium') return Number(product.price_premium || 0);

        // Default to Regular price
        return Number(product.price_regular || 0);
    },

    /**
     * Automatically converts Google Drive sharing links to direct image links
     * @param {string} url 
     * @returns {string} transformed url
     */
    transformDriveUrl: (url) => {
        if (!url || typeof url !== 'string') return url;
        if (url.includes('drive.google.com')) {
            // Extract the ID from /file/d/ID/view or ?id=ID
            const driveId = url.split('/d/')[1]?.split('/')[0] || url.split('id=')[1]?.split('&')[0];
            if (driveId) {
                // Use the thumbnail endpoint which is much more reliable for embedding in <img> tags
                return `https://drive.google.com/thumbnail?id=${driveId}&sz=w1000`;
            }
        }
        return url;
    },

    /**
     * Determine category based on product name
     */
    getCategoryByName: (name = "") => {
        const n = name.toLowerCase();
        if (n.includes("beras")) return "Beras";
        if (n.includes("minyak") || n.includes("mentega") || n.includes("blue band")) return "Minyak, Mentega & Lemak";
        if (n.includes("tepung") || n.includes("panir") || n.includes("tapioka") || n.includes("terigu")) return "Tepung-Tepungan";
        if (n.includes("saos") || n.includes("kecap") || n.includes("sambal") || n.includes("saori")) return "Saus, Kecap & Sambal";
        if (
            n.includes("gula") ||
            n.includes("garam") ||
            n.includes("kaldu") ||
            n.includes("totole") ||
            n.includes("santan") ||
            n.includes("kara") ||
            n.includes("sasa") ||
            n.includes("fiber creme") ||
            n.includes("powder")
        ) return "Bumbu & Bahan Masak";
        return "Lainnya";
    },

    /**
     * Migration helper to categorize all existing products
     */
    migrateCategories: async () => {
        const col = getCollectionName("products");
        const snapshot = await getDocs(collection(db, col));
        const updates = snapshot.docs.map(async (d) => {
            const product = { id: d.id, ...d.data() };
            if (!product.category || product.category === 'Lainnya') {
                const category = productService.getCategoryByName(product.name);
                if (category !== 'Lainnya') {
                    await productService.saveProduct({ product_id: product.id, category });
                }
            }
        });
        await Promise.all(updates);
    }
};
